Fixed typo in rtc_config_example.json
schlagmichdoch/PairDrop pull request #345
Opened 2024-10-27 23:21 UTC by shommey

"urls": "turns:<DOMAIN>:5349" changed to
"urls": "turn:<DOMAIN>:5349"

This little oversight costed me a few hours of my life I'll never get back. :)

2024-10-28 12:01 UTC, schlagmichdoch commented
`turns::5349` is the correct way if you want TURN over TLS. (See https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#coturn-and-pairdrop-via-docker-compose)

If you want to implement TURN without additional TLS encryption (which is fine) you should use `turn::3478` as this is the standard port for STUN and TURN without TLS or change the port to whatever you have specified in your _turnserver.conf_. (See https://github.com/schlagmichdoch/PairDrop/blob/ce3d5698802b040eb9e55cf4a2abc06032e4672e/turnserver_example.conf#L12)

So I can't merge this PR as it is. 

Maybe the `turn::3478` config should be included additionally to the two existing or we should have different config files for TURN with and w/o TLS. What do you think?

Where did you take a look for the configuration? I guess this could also be solved by a simple reference of the different versions (`stun:`, `turn:`, `turns:`) in the docs here: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#specify-stunturn-servers

2024-10-28 20:04 UTC, shommey commented
I see, sorry for the mix up then.
I think the docs should mention that "s" in the "turns" stands for turn tls.
It could be great if `turn:` and `turns:` difference could be pointed out in .json itself.

2025-02-11 09:33 UTC, schlagmichdoch commented
Sorry for the late reply. Trying to catch up with the issue built-up.


> It could be great if `turn:` and `turns:` difference could be pointed out in .json itself.

How about we duplicate the turn server part:
```json
{
  "sdpSemantics": "unified-plan",
  "iceServers": [
    {
      "urls": "stun:<DOMAIN>:3478"
    },
    {
      "urls": "turn:<DOMAIN>:5349",
      "username": "username",
      "credential": "password"
    }
  ]
}

2025-02-11 09:35 UTC, schlagmichdoch requested changes
turn over tls description. See comment in conversation

2026-09-15 23:08 UTC, closed without merging